package var;

public interface VariableXpath {
    String btn_login = "//a[text()='Login']";
    String btn_lanjutkan = "//*[@type='button' and contains(text(),'Lanjut')]";
    String btn_logon = "//*[@type='button' and contains(text(),'Log')]";
    String field_email = "//*[@name='username' and @type='text']";
    String field_pass = "//*[@name='password' and @type='password']";
    String label_tiket = "//*[@alt='logo tiket.com']";
    String btn_pesawat = "//div/img[contains(@alt,'Pesawat')]";
    String btn_keretaapi = "//div/img[contains(@alt,'Kereta')]";
    String rdo_oneway = "//*[contains(@id,'oneWay')]/following-sibling::*";
    String rdo_round = "//*[contains(@id,'round')]/following-sibling::*";
    String field_from = "//input[@id='productSearchFrom']";
    String field_to = "//input[@id='productSearchTo']";
    String field_from_tr = "//input[@class='input-airport ' and @tabindex='1']";
    String field_to_tr = "//input[@class='input-airport ' and @tabindex='2']";
    String field_dep_date_tr = "//input[@tabindex='3']";
    String field_pass_tr = "//input[@tabindex='4']";
    String ddc_from_tr = "//*[@class='station-city']/span";
    String ddc_to_tr  = "//*[@class='station-city']/span";
    String field_dep_date = "//input[@id='productSearchDeparture']";
    String field_ret_date = "//input[@id='productSearchReturn']";
    String field_pass_cabin = "//input[@id='productSearchPassengerCabin']";
    String ddc_from = "//*[@id='fromDropDownList-airport1']//*[@class='drop-down-option-content']/div";
    String ddc_to = "//*[@id='toDropDownList-airport1']";
    String date_dep_tr = "//*[text()='Hari ini']/parent::*/parent::*/following-sibling::*/div";
    String date_dep = "//*[text()='Hari ini']/parent::*/parent::*/following-sibling::*/div//span";
    String date_back = "//*[contains(@class,'selected')]/following-sibling::*/div/span";
    String inc_adult = "//*[@class='widget-passenger-cabin-type' and text()='Dewasa']/parent::*/following-sibling::*//i[@class='tix tix-plus']";
    String inc_adult_tr = "//*[@class='passenger-type' and text()='Dewasa']/parent::*/following-sibling::*//i[@class='tix tix-plus icon']";
    String inc_infant_tr = "//*[@class='passenger-type' and text()='Bayi']/parent::*/following-sibling::*//i[@class='tix tix-plus icon']";
    String inc_kid = "//*[@class='widget-passenger-cabin-type' and text()='Anak']/parent::*/following-sibling::*//i[@class='tix tix-plus']";
    String inc_infant = "//*[@class='widget-passenger-cabin-type' and text()='Bayi']/parent::*/following-sibling::*//i[@class='tix tix-plus']";
    String btn_ekonomi = "//*[@class='passenger-cabin-content-list']//*[text()='Ekonomi']";
    String btn_selesai = "//*[text()='SELESAI']";
    String btn_selesai_tr = "//*[text()='Selesai']";
    String btn_cari_flight = "//button[text()='CARI PENERBANGAN']";
    String btn_cari_tr = "//button[text()='Cari Kereta Api']";
    String btn_mengerti = "//div[text()='Mengerti']";
    String chkbox_filter_transit_langsung = "//label[@for='direct']";
    String chkbox_filter_transit_1 = "//label[@for='stop']";
    String chkbox_filter_transit_2 = "//label[@for='stops']";
    String chkbox_filter_waktu_berangkat_1 = "//label[@for='departure_dawn']";
    String chkbox_filter_waktu_berangkat_2 = "//label[@for='departure_morning']";
    String chkbox_filter_waktu_berangkat_3 = "//label[@for='departure_afternoon']";
    String chkbox_filter_waktu_berangkat_4 = "//label[@for='departure_evening']";
    String chkbox_filter_waktu_tiba_1 = "//label[@for='arrival_dawn']";
    String chkbox_filter_waktu_tiba_2 = "//label[@for='arrival_morning']";
    String chkbox_filter_waktu_tiba_3 = "//label[@for='arrival_afternoon']";
    String chkbox_filter_waktu_tiba_4 = "//label[@for='arrival_evening']";
    String slider_filter_durasi_transit = "//*[@class='content-filter']/div[2]//div[@class='rc-slider tiket-slider']";
    String slider_filter_durasi_perjalanan = "//*[@class='content-filter']/div[8]//div[@class='rc-slider tiket-slider']";
    String chkbox_filter_jenis_tarif_clean = "//label[@for='tiketcleanmultilabelmultilabel']";
    String chkbox_filter_jenis_tarif_flexy = "//label[@for='tiketfleximultilabelmultilabel']";
    String chkbox_filter_fasilitas_bagasi = "//label[@for='baggagemultilabelmultilabel']";
    String chkbox_filter_fasilitas_hiburan = "//label[@for='entertainmentmultilabelmultilabel']";
    String chkbox_filter_fasilitas_makanan = "//label[@for='mealmultilabelmultilabel']";
    String btn_pilih_penerbangan = "//*[@class='section-box-content']/div[1]//*[@class='btn-book-now']/*[text()='PILIH']";
    String lbl_penerbangan_pergi = "//*[contains(text(),'Penerbangan Pergi')]";
    String lbl_penerbangan_pulang = "//*[contains(text(),'Penerbangan Pulang')]";
    String swc_same_with_acc = "//*[@class='switch']/span";
    String ddl_nationality= "//*[@class='title-flight-dropdown-searchbox' and text()='Kewarganegaraan']";
    String ddl_nationality_idr= "//*[@class='list-horizontal__middle' and text()='Indonesia']";
    String btn_goes_to_payment = "//*[text()='LANJUTKAN KE PEMBAYARAN']";
    String btn_confirm = "//*[text()='YA, LANJUTKAN']";
    String btn_bca_va = "//*[contains(text(),'BCA Virtual')]";
    String btn_payment_continue = "//button[contains(text(),'Lanjut')]";
    String lbl_va_number = "//div[@class='va-number-number']/p";
    String header_acc = "//div[@class='header-account']/span";
    String btn_keluar = "//div[@class='account-item-container']/span[text()='Keluar']";
    String btn_keluar_confirm = "//div[@class='logout-button']/button[text()='YA']";
    String btn_optional_train_ok = "//button[text()='OK']";
}

